<?xml version="1.0" encoding="utf-8"?><Database Name="dbListRecipients1" Class="RecipientsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|dbListRecipients1.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="WpfMailSender.Properties.Settings" SettingsPropertyName="dbListRecipients1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Emails">
    <Type Name="Emails">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>